# These variables define the project; they may not need to be changed
project:
  type: book
  output-dir: _book

# These variables define the book contents - adjust them as necessary
book:
  # [A] BOOK TITLE
  title: "pyANI-plus"
  reader-mode: true
  
  # The cover image and favicon; these may not need to be changed
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  
  # Sets the page footer text/images
  # [B] FOOTER TEXT
  page-footer:
    left: |
      pyANI-plus documentation
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  # Sets the URL for the repository
  # [C] GITHUB REPOSITORY URL
  repo-url: https://github.com/sipbs-compbiol/REPOSITORY
  repo-branch: main
  repo-actions: [edit, issue]

  # Sets author information and publication/presentation date
  # [D] AUTHOR INFORMATION AND PUBLICATION/PRESENTATION DATE
  author: "Leighton Pritchard"
  date: "03/10/2025"

  # Define chapters and sections here
  # [E] CHAPTERS AND SECTIONS
  chapters:
    - index.qmd
    - requirements.qmd
    - installation.qmd
    - walkthrough.qmd

    - part: subcommands/subcommands.qmd
      chapters: 
        - subcommands/anib.qmd
        - subcommands/anim.qmd
        - subcommands/dnadiff.qmd
        - subcommands/external_alignment.qmd
        - subcommands/fastani.qmd
        - subcommands/sourmash.qmd
        - subcommands/plot_run.qmd
        - subcommands/plot_run_comp.qmd
        - subcommands/list_runs.qmd
        - subcommands/export_run.qmd
        - subcommands/resume.qmd
        - subcommands/delete_run.qmd
        - subcommands/classify.qmd
    - testing.qmd
    - part: licensing.qmd
      chapters: 
        - pyani_licence.qmd
        - doc_licence.qmd


# Location of BibTeX format reference file; may not need to be changed
bibliography: references.bib

# Formatting and theme; may not need to be changed
format:
  html:
    theme: cosmo
    code-link: true
    
    author-meta: "Leighton Pritchard"
  
  pdf:
    documentclass: scrreprt

# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto

