# Contributing to `pyANI-plus` {#sec-contributing .unnumbered}

## Reporting bugs and errors
If you find a bug, or an error in the code or documentation, please report this by raising an issue at the [GitHub issue page](https://github.com/pyani-plus/pyani-plus/issues) for `pyANI-plus`. 


## Contributing code or documentation
We welcome contributions of all kinds! Check out the GitHub contributors link for a list of those who have helped shape the project.

Whether you’d like to develop `pyANI-plus`, fix a bug, or improve documentation, your help is appreciated! To help maintain an efficient workflow, please adhere to the developer guidelines below:

### Making changes and pull requests

1. Fork the `pyANI-plus` [repository](https://github.com/pyani-plus/pyani-plus) under your [GitHub](https://github.com/) account.  
2. Clone the forked repository to your local development machine.  

   - To edit `pyANI-plus` and see changes take effect immediately (without reinstalling), run:  
     ```sh
     pip install -e .
     ```
     inside the cloned repository. This is useful for testing.  

3. Create a new branch in your forked repository with an informative name such as `fix_issue_107`, by running:  
   ```sh
   git checkout -b fix_issue_107
   ```  
4. Make the changes you need and commit them to your local branch.  
5. Run the `pytests` in the respoitory to ensure your changes work and do not intriduce any bugs or errors (see the [testing documentation](testing.qmd#testing))

6. If the tests all pass, push the changes to your fork, and submit a pull request against the original repository.

7. Indicate one of the `pyANI-plus` developers as an assignee in your pull request. A developer will review your pull request and either merge it or provide feedback for further improvements.  



## Suggestions for improvement
We appreciate your feedback on `pyANI-plus`. If you have a specific issue or proposal, please submit it through [GitHub Issues](https://github.com/pyani-plus/pyani-plus/issues). To discuss ideas with the maintainers and community, join the conversation on [GitHub Discussions](https://github.com/pyani-plus/pyani-plus/discussions/landing).